### ISSUE TITLE
PHP Fatal error:  Class 'LeaveCalendarForm' not found

### ISSUE THREAD

**Issue by nileshpoman** [nikoloup/orangehrm3-calendar#2]
Hi

I have install this leave calendar but it give an following error
"PHP Fatal error:  Class 'LeaveCalendarForm' not found in /orangehrm/symfony/plugins/orangehrmLeavePlugin/modules/leave/actions/viewLeaveCalendarAction.class.php on line 92".
I have also add the LeaveCalendarForm.php on this path /symfony/plugins/orangehrmLeavePlugin/lib/form/  but still it give an above error please help me ASAP. 
my site is this http://orangehrm.nysainfotechdev.co.in/symfony/web/index.php/
user name:- Admin
pass :- admin@123
Thanks

**Comment by nikoloup** [comment]
I'm sorry I couldn't help you, I unfortunately no longer had time to support this.

I hope you found a solution to your problem.
Regards,
Panos
